### ISSUE TITLE
Example of data sources

### ISSUE THREAD

**Issue by iamyifan** [southern-cross-ai/training-data-creator#1]
Hey Umar, 

I found 2 data resources from ANU and U. of Canberra (UC):

- [Australian Legal Databases - ANU](https://libguides.anu.edu.au/c.php?g=634887&p=4446792)
- [Key Australian Databases - UC](https://canberra.libguides.com/c.php?g=924082&p=6788174)

There are several databases listed inside. I just want to make sure it is the right format.

Cheers,
Yifan 
TechLauncher Project

**Comment by umarbutler** [comment]
Hi Yifan,
Unforunately, none of the databases in both links are available under open-source licences. Please feel free not to limit yourself to Australian law. I included legal data as a starting point but we want to have a diverse range of data sources, including non-Australian sources, as the end-goal is to produce a general LLM for multiple languages, ideally (but at least general English).
